<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Shared.Kernel\Shared.Kernel.csproj" />
    <ProjectReference Include="..\Shared.Modularity\Shared.Modularity.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>


</Project>
